- name: Install Development Packages
  become: true
  become_user: root
  block:
  - name: Install C/C++ Deps
    community.general.xbps:
      name:
        - gcc
        - clang
        - make
  - name: Install Rust Deps
    block:
      - name: Download Rustup
        ansible.builtin.get_url:
          url: https://sh.rustup.rs
          dest: /tmp/rustup-init.sh
          # TODO add checksum
          mode: 0755
      - name: Bootstrap Rustup
        become: yes
        become_user: "{{ ansible_user_id }}"
        shell: /tmp/rustup-init.sh --default-toolchain nightly -y
        vars:
          allow_world_readable_tmpfiles: true
      - name: Source the rustup env
        become: yes
        become_user: "{{ ansible_user_id }}"
        shell: source $HOME/.cargo/env
        args:
          executable: /bin/bash

  - name: Install Neovim Deps
    community.general.xbps:
      name:
        - nodejs-lts
        - curl
        - tree-sitter
        - tree-sitter-devel

- name: Bootstrap Neovim Plugins
  block:
    - name: Install Packer
      ansible.builtin.command:
        nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
      changed_when: false

- name: Setup development workspace
  block:
    - name: Create workspace folder
      block:
        - name: Check for workspace folder
          ansible.builtin.stat:
            path: $HOME/workspace/
          register: git_proj_workspace_dir
        - name: Create folder
          ansible.builtin.file:
            path: $HOME/workspace
            state: directory
            mode: 0755
          when:
            git_proj_workspace_dir.stat.exists
    - name: Update playbook repository
      block:
        - name: Collect playbook directory info
          ansible.builtin.stat:
            path: $HOME/workspace/playbook/
          register: git_playbook_dir
        - name: Fast forward repo
          ansible.builtin.git:
            repo: git@github.com:freylint/playbook.git
            dest: $HOME/workspace/playbook/
            refspec: +refs/pull/*:refs/heads/*
          when: git_playbook_dir.stat.exists
          # Ignore errors due to failure if working tree is dirty
          ignore_errors: true
        - name: Clone playbook repo
          ansible.builtin.git:
            repo: git@github.com:freylint/playbook.git
            dest: $HOME/workspace/playbook/
          when: not git_playbook_dir.stat.exists
    - name: Update freyground repository
      block:
        - name: Collect freyground directory info
          ansible.builtin.stat:
            path: $HOME/workspace/freyground/
          register: git_freyground_dir
        - name: Fast forward repo
          ansible.builtin.git:
            repo: git@github.com:freylint/freyground.git
            dest: $HOME/workspace/freyground/
            refspec: +refs/pull/*:refs/heads/*
          when: git_freyground_dir.stat.exists
        - name: Clone freyground repo
          ansible.builtin.git:
            repo: git@github.com:freylint/freyground.git
            dest: $HOME/workspace/freyground/
          when: not git_playbook_dir.stat.exists

